move the inputs on a different line then their label, adjust button t…
fab514/project-one pull request #65
Opened 2021-06-07 01:33 UTC by fab514

…o match rest of layout

2021-06-07 02:43 UTC, Sonic12040 commented
I think a little more time should be put into this mobile layout. Most people visit these types of pages on their mobile devices. Perhaps visit your site on your mobile device, and see what is easy for you. What proves difficult? How do other sites handle mobile interfaces? What do you like about the interface of your favorite mobile applications?

2021-06-07 02:43 UTC, Sonic12040 requested changes

2021-06-07 02:43 UTC, Sonic12040 commented on index.html
> +                <div class="button">
I think you can get rid of this wrapper and just style the button itself, and I would say take advantage of the color scheme that you have come up with for this site and the visual language of the other elements on the page.
What does the button look like when it isn't being used? What about when you hover over it? What about while you're clicking on it?

2021-06-07 02:43 UTC, Sonic12040 commented on index.html
> +                <div name="select">
Why is this wrapping div needed?

2021-06-07 04:56 UTC, fab514 commented
Colored css body and added the activity image.

2021-06-07 16:32 UTC, Sonic12040 commented
I would try something like:
```html

            <label name="label">
                Participants
                <br>
                <input class="input" type="number" name="participants" value="1" min="1" max="100">
            </label>
            <label name="label">
                    Activity Type
                <select name="type" class="select">
                    <option value="">Any</option>
                    <option value="cooking">Cooking</option>
                    <option value="education">Education</option>
                    <option value="social">Social</option>
                    <option value="recreational">Recreational</option>
                    <option value="busywork">Busywork</option>
                    <option value="charity">Charity</option>
                    <option value="relaxation">Relaxation</option>
                    <option value="diy">DIY</option>
                    <option value="music">Music</option>
                </select></label>
            <div class="search">
                <button>Search</button>
            </div>
        ```
        And use CSS like display: block to bump the select to the next line from the label.

2021-06-07 16:34 UTC, Sonic12040 requested changes
Just the item I mentioned above. This is looking great!

2021-06-08 03:59 UTC, Sonic12040 approved these changes

2021-06-08 03:59 UTC, merged